language: csharp
solution: health-data-repository.sln
mono: none
dotnet: 2.1

# Specify which branches can be built on PR merge
branches:
  only:
    - master
    - development

script:
- dotnet restore

notifications:
    slack: sem5640-2018:qMQqfa3QEJnk6K0yHcT7KMg0
